#!/bin/bash

#DNS server reference:

#TaiWan Chunghwa Telecom DNS
#168.95.1.1（dns.hinet.net）
#168.95.192.1（hntp1.hinet.net）
#168.95.192.2（hntp3.hinet.net）
#202.45.84.58 (HK)
#8.8.8.8 / 8.8.4.4  (Google Public DNS)
#202.101.172.35 (China telecom)
#202.12.27.33 (Japan)
#root dns server
#A.root-servers.net 198.41.0.4         US
#B.root-servers.net 192.228.79.201     US
#C.root-servers.net 192.33.4.12        FR
#D.root-servers.net 128.8.10.90        US 
#E.root-servers.net 192.203.230.10     US 
#F.root-servers.net 192.5.5.241        US
#G.root-servers.net 192.112.36.4       US
#H.root-servers.net 128.63.2.53        US 
#I.root-servers.net 192.36.148.17      SE
#J.root-servers.net 192.58.128.30      US
#K.root-servers.net 193.0.14.129       EN 
#L.root-servers.net 198.32.64.12       US
#M.root-servers.net 202.12.27.33       JP

dns_server="202.45.84.58" #default DNS server for nslookup

#for mode 1
dns_download_url="https://smarthosts.googlecode.com/svn/trunk/hosts"

userdef_hosts () {
    #user-defined DNS 
    echo "127.0.0.1            localhost"
    echo "127.0.1.1            `hostname`"
    echo ""
    echo "# The following lines are desirable for IPv6 capable hosts"
    echo "::1                  ip6-localhost ip6-loopback"
    echo "fe00::0              ip6-localnet"
    echo "ff00::0              ip6-mcastprefix"
    echo "ff02::1              ip6-allnodes"
    echo ":ff02::2             ip6-allrouters"
    echo "74.125.135.141       www.panoramio.com"
}

usage () {
    echo "Usage: $1 [DNS-server]"
    echo "   DNS-server: --generate Hosts by nslookup"
    echo "               if '-1' --get Hosts from $dns_download_url"
}

#script_fn=`realpath $0`
script_fn=$0

# mode: "0" generate Hosts by nslookup(default). 
# mode: "1" for get hosts from $dns_download_url
upmode=0
if [ ! -z "$1" ] && [ "$1" = "-1" ];then
    upmode=1
fi

if [ $upmode -eq 1 ];then
   wget $dns_download_url --no-check-certificate -O /tmp/newhosts
   if [ -r /tmp/newhosts ];then
       echo "#hosts upgrade by update_hosts" >/tmp/hosts
       userdef_hosts >>/tmp/hosts
       cat /tmp/newhosts |sed '/127.0.0.1/ d'|sed 's/\r//g' >>/tmp/hosts
       md5_etc_hosts=`md5sum /etc/hosts |awk '{print $1}'`
       md5_tmp_hosts=`md5sum /tmp/hosts |awk '{print $1}'`
       echo "hosts                etc                       tmp"
       if [ "$md5_etc_hosts" != "$md5_tmp_hosts" ];then
         echo -e "[\033[01;31mDIFF\033[00m]  $md5_etc_hosts -- $md5_tmp_hosts"
         echo -e "update hosts? [\033[01;31my\033[00m]/[\033[01;31mn\033[00m]"
         read user_in
         if [ $user_in = "Y" -o $user_in = "y" -o $user_in = "yes" ];then
             sudo cp -v /tmp/hosts /etc/hosts
             sudo service resolvconf restart
         fi
       else
         echo -e "[\033[01;31mSAME\033[00m]  $md5_etc_hosts -- $md5_tmp_hosts"
       fi
   fi
   exit 0
fi

if [ -z "$1" ];then
   echo "# Use default DNS server:$dns_server for nslookup"
   echo "# Specify a DNS server use '$0 [dns-server]'"
else
   dns_server=$1
fi
echo "# Update: `date`"
userdef_hosts
echo ""
echo "# Auto generate by nslookup" 
hs_list_stline=`grep  -n "hosts_list" $script_fn|sed '/grep/ d'|awk -F : '{print $1}'` 
hs_list_stline=$(($hs_list_stline+1))
urls=`tail -n+$hs_list_stline $script_fn |xargs`
for url in $urls
do
    trynum=3
    while true;do
    ipaddr=`nslookup $url $dns_server \
             |grep Address:|awk 'NR==2{print $2}'`
    if [ ! -z "$ipaddr" ];then
        printf "%-20s %s\n" $ipaddr $url
        break
    fi
    trynum=$((trynum-1))
    if [ $trynum -eq 0 ];then
        break
    fi
    sleep 0.2
    done
done

exit 0

----hosts_list----
0.docs.google.com
0.drive.google.com
1.docs.google.com
1.drive.google.com
10.docs.google.com
10.drive.google.com
11.docs.google.com
11.drive.google.com
12.docs.google.com
12.drive.google.com
13.docs.google.com
13.drive.google.com
14.docs.google.com
14.drive.google.com
15.docs.google.com
15.drive.google.com
16.docs.google.com
16.drive.google.com
2.docs.google.com
2.drive.google.com
3.docs.google.com
3.drive.google.com
4.docs.google.com
4.drive.google.com
5.docs.google.com
5.drive.google.com
6.docs.google.com
6.drive.google.com
7.docs.google.com
7.drive.google.com
8.docs.google.com
8.drive.google.com
9.docs.google.com
9.drive.google.com
accounts.google.com
accounts.l.google.com
answers.google.com
apis.google.com
appengine.google.com
apps.google.com
appspot.l.google.com
bks0.books.google.com
bks1.books.google.com
bks10.books.google.com
bks2.books.google.com
bks3.books.google.com
bks4.books.google.com
bks5.books.google.com
bks6.books.google.com
bks7.books.google.com
bks8.books.google.com
bks9.books.google.com
blogsearch.google.com
books.google.com
browserchannel-docs.l.google.com
browserchannel-spreadsheets.l.google.com
browsersync.google.com
browsersync.l.google.com
buzz.google.com
cache.l.google.com
cache.pack.google.com
calendar.google.com
cbk0.google.com
cbk1.google.com
cbk2.google.com
cbk3.google.com
cbks0.google.com
cbks1.google.com
cbks2.google.com
cbks3.google.com
chart.apis.google.com
chatenabled.mail.google.com
checkout.google.com
checkout.l.google.com
chrome.google.com
clients.l.google.com
clients1.google.com
clients2.google.com
clients3.google.com
clients4.google.com
clients5.google.com
clients6.google.com
clients7.google.com
code.google.com
code.l.google.com
csi.l.google.com
desktop.google.com
desktop.l.google.com
desktop2.google.com
developers.google.com
ditu.google.com
dl.google.com
dl.l.google.com
dl-ssl.google.com
docs.google.com
docs0.google.com
docs1.google.com
docs2.google.com
docs3.google.com
docs4.google.com
docs5.google.com
docs6.google.com
docs7.google.com
docs8.google.com
docs9.google.com
drive.google.com
drive0.google.com
drive1.google.com
drive2.google.com
drive3.google.com
drive4.google.com
drive5.google.com
drive6.google.com
drive7.google.com
drive8.google.com
drive9.google.com
earth.google.com
encrypted.google.com
encrypted-tbn.l.google.com
encrypted-tbn0.google.com
encrypted-tbn1.google.com
encrypted-tbn2.google.com
encrypted-tbn3.google.com
feedburner.google.com
feedproxy.google.com
filetransferenabled.mail.google.com
finance.google.com
fusion.google.com
geoauth.google.com
gg.google.com
ghs.google.com
ghs.l.google.com
ghs46.google.com
ghs46.l.google.com
google.com
googleapis.l.google.com
googleapis-ajax.google.com
googleapis-ajax.l.google.com
googlecode.l.google.com
google-public-dns-a.google.com
google-public-dns-b.google.com
goto.google.com
groups.google.com
groups.l.google.com
groups-beta.google.com
gxc.google.com
id.google.com
id.l.google.com
images.google.com
images.l.google.com
investor.google.com
jmt0.google.com
kh.google.com
kh.l.google.com
khm.google.com
khm.l.google.com
khm0.google.com
khm1.google.com
khm2.google.com
khm3.google.com
khmdb.google.com
khms.google.com
khms.l.google.com
khms0.google.com
khms1.google.com
khms2.google.com
khms3.google.com
labs.google.com
large-uploads.l.google.com
lh2.google.com
lh2.l.google.com
lh3.google.com
lh4.google.com
lh5.google.com
lh6.google.com
linkhelp.clients.google.com
local.google.com
m.google.com
mail.google.com
map.google.com
maps.google.com
maps.l.google.com
maps-api-ssl.google.com
mars.google.com
mobile.l.google.com
mobile-gtalk.l.google.com
mobilemaps.clients.google.com
mt.google.com
mt.l.google.com
mt0.google.com
mt1.google.com
mt2.google.com
mt3.google.com
mtalk.google.com
mts.google.com
mts.l.google.com
mts0.google.com
mts1.google.com
mts2.google.com
mts3.google.com
music.google.com
music-streaming.l.google.com
mw1.google.com
mw2.google.com
news.google.com
news.l.google.com
pack.google.com
photos.google.com
photos-ugc.l.google.com
picasa.google.com
picasaweb.google.com
picasaweb.l.google.com
places.google.com
play.google.com
productforums.google.com
profiles.google.com
reader.google.com
safebrowsing.cache.l.google.com
safebrowsing.clients.google.com
safebrowsing.google.com
safebrowsing-cache.google.com
sandbox.google.com
sb.google.com
sb.l.google.com
sb-ssl.google.com
sb-ssl.l.google.com
scholar.google.com
scholar.l.google.com
script.google.com
services.google.com
sites.google.com
sketchup.google.com
sketchup.l.google.com
spreadsheet.google.com
spreadsheets.google.com
spreadsheets.l.google.com
spreadsheets0.google.com
spreadsheets1.google.com
spreadsheets2.google.com
spreadsheets3.google.com
spreadsheets4.google.com
spreadsheets5.google.com
spreadsheets6.google.com
spreadsheets7.google.com
spreadsheets8.google.com
spreadsheets9.google.com
spreadsheets-china.l.google.com
suggestqueries.google.com
suggestqueries.l.google.com
support.google.com
talk.google.com
talkgadget.google.com
tbn0.google.com
tbn1.google.com
tbn2.google.com
tbn3.google.com
toolbar.google.com
toolbarqueries.clients.google.com
toolbarqueries.google.com
toolbarqueries.l.google.com
tools.google.com
tools.l.google.com
translate.google.com
trends.google.com
upload.docs.google.com
upload.drive.google.com
uploads.code.google.com
uploadsj.clients.google.com
v3.cache1.c.docs.google.com
video.google.com
video-stats.l.google.com
voice.google.com
wallet.google.com
wifi.google.com
wifi.l.google.com
wire.l.google.com
writely.google.com
writely.l.google.com
writely-china.l.google.com
writely-com.l.google.com
www.google.com
www.l.google.com
www2.l.google.com
www3.l.google.com
www4.l.google.com
ytstatic.l.google.com
0-open-opensocial.googleusercontent.com
0-focus-opensocial.googleusercontent.com
1-focus-opensocial.googleusercontent.com
1-open-opensocial.googleusercontent.com
1-ps.googleusercontent.com
2-focus-opensocial.googleusercontent.com
2-open-opensocial.googleusercontent.com
2-ps.googleusercontent.com
3-focus-opensocial.googleusercontent.com
3-ps.googleusercontent.com
3hdrrlnlknhi77nrmsjnjr152ueo3soc-a-calendar-opensocial.googleusercontent.com
3-open-opensocial.googleusercontent.com
4-ps.googleusercontent.com
4fjvqid3r3oq66t548clrdj52df15coc-a-oz-opensocial.googleusercontent.com
53rd6p0catml6vat6qra84rs0del836d-a-oz-opensocial.googleusercontent.com
59cbv4l9s05pbaks9v77vc3mengeqors-a-oz-opensocial.googleusercontent.com
8kubpeu8314p2efdd7jlv09an9i2ljdo-a-oz-opensocial.googleusercontent.com
adstvca8k2ooaknjjmv89j22n9t676ve-a-oz-opensocial.googleusercontent.com
a-oz-opensocial.googleusercontent.com
blogger.googleusercontent.com
bt26mravu2qpe56n8gnmjnpv2inl84bf-a-oz-opensocial.googleusercontent.com
clients1.googleusercontent.com
clients2.googleusercontent.com
clients3.googleusercontent.com
clients4.googleusercontent.com
clients5.googleusercontent.com
clients6.googleusercontent.com
clients7.googleusercontent.com
code-opensocial.googleusercontent.com
debh8vg7vd93bco3prdajidmm7dhql3f-a-oz-opensocial.googleusercontent.com
doc-00-7o-docs.googleusercontent.com
doc-08-7o-docs.googleusercontent.com
doc-0c-7o-docs.googleusercontent.com
doc-0g-7o-docs.googleusercontent.com
doc-0s-7o-docs.googleusercontent.com
doc-10-7o-docs.googleusercontent.com
doc-14-7o-docs.googleusercontent.com
feedback.googleusercontent.com
googlehosted.l.googleusercontent.com
gp0.googleusercontent.com
gp1.googleusercontent.com
gp2.googleusercontent.com
gp3.googleusercontent.com
gp4.googleusercontent.com
gp5.googleusercontent.com
gp6.googleusercontent.com
hsco54a20sh11q9jkmb51ad2n3hmkmrg-a-oz-opensocial.googleusercontent.com
i8brh95qor6r54nkl52hidj2ggcs4jgm-a-oz-opensocial.googleusercontent.com
images1-focus-opensocial.googleusercontent.com
images2-focus-opensocial.googleusercontent.com
images3-focus-opensocial.googleusercontent.com
images4-focus-opensocial.googleusercontent.com
images5-focus-opensocial.googleusercontent.com
images6-focus-opensocial.googleusercontent.com
images7-focus-opensocial.googleusercontent.com
images8-focus-opensocial.googleusercontent.com
images9-focus-opensocial.googleusercontent.com
images-docs-opensocial.googleusercontent.com
images-oz-opensocial.googleusercontent.com
k6v18tjr24doa89b55o3na41kn4v73eb-a-oz-opensocial.googleusercontent.com
lh1.googleusercontent.com
lh2.googleusercontent.com
lh3.googleusercontent.com
lh4.googleusercontent.com
lh5.googleusercontent.com
lh6.googleusercontent.com
mail-attachment.googleusercontent.com
music.googleusercontent.com
music-onebox.googleusercontent.com
oauth.googleusercontent.com
ob7f2qc0i50kbjnc81vkhgmb5hsv7a8l-a-oz-opensocial.googleusercontent.com
ode25pfjgmvpquh3b1oqo31ti5ibg5fr-a-calendar.opensocial.googleusercontent.com
qhie5b8u979rnch1q0hqbrmbkn9estf7-a-oz-opensocial.googleusercontent.com
r70rmsn4s0rhk6cehcbbcbfbs31pu0va-a-oz-opensocial.googleusercontent.com
rbjhe237k979f79d87gmenp3gejfonu9-a-oz-opensocial.googleusercontent.com
s1.googleusercontent.com
s2.googleusercontent.com
s3.googleusercontent.com
s4.googleusercontent.com
s5.googleusercontent.com
s6.googleusercontent.com
spreadsheets-opensocial.googleusercontent.com
static.googleusercontent.com
t.doc-0-0-sj.sj.googleusercontent.com
themes.googleusercontent.com
translate.googleusercontent.com
u807isd5egseeabjccgcns005p2miucq-a-oz-opensocial.googleusercontent.com
upt14k1i2veesusrda9nfotcrbp9d7p5-a-oz-opensocial.googleusercontent.com
webcache.googleusercontent.com
www.googleusercontent.com
www-calendar-opensocial.googleusercontent.com
www-fc-opensocial.googleusercontent.com
www-focus-opensocial.googleusercontent.com
www-gm-opensocial.googleusercontent.com
www-kix-opensocial.googleusercontent.com
www-open-opensocial.googleusercontent.com
www-opensocial.googleusercontent.com
www-opensocial-sandbox.googleusercontent.com
www-oz-opensocial.googleusercontent.com
ajax.googleapis.com
chart.googleapis.com
fonts.googleapis.com
maps.googleapis.com
mt0.googleapis.com
mt1.googleapis.com
mt2.googleapis.com
mt3.googleapis.com
redirector-bigcache.googleapis.com
translate.googleapis.com
www.googleapis.com
autoproxy-gfwlist.googlecode.com
chromium.googlecode.com
closure-library.googlecode.com
earth-api-samples.googlecode.com
gmaps-samples-flash.googlecode.com
google-code-feed-gadget.googlecode.com
blogsearch.google.cn
ditu.google.cn
gg.google.cn
id.google.cn
m.google.cn
mt.google.cn
mt0.google.cn
mt1.google.cn
mt2.google.cn
mt3.google.cn
news.google.cn
scholar.google.cn
translate.google.cn
www.google.cn
accounts.google.com.hk
blogsearch.google.com.hk
books.google.com.hk
clients1.google.com.hk
desktop.google.com.hk
encrypted.google.com.hk
groups.google.com.hk
gxc.google.com.hk
id.google.com.hk
images.google.com.hk
m.google.com.hk
maps.google.com.hk
news.google.com.hk
picasaweb.google.com.hk
plus.url.google.com.hk
scholar.google.com.hk
toolbar.google.com.hk
toolbarqueries.google.com.hk
translate.google.com.hk
translate.google.com.hk
wenda.google.com.hk
www.google.com.hk
android.googlesource.com
domains.googlesyndication.com
earthengine.googlelabs.com
listen.googlelabs.com
m.googlemail.com
ngrams.googlelabs.com
smarthosts.googlecode.com
ssl.google-analytics.com
www.googleadservices.com
www.google-analytics.com
www.googlelabs.com
www.googlesource.com
plus.google.com
plus.url.google.com
plusone.google.com
ytimg.l.google.com
